CREATE TABLE
  IF NOT EXISTS `session` (
    `id` TEXT NOT NULL PRIMARY KEY,
    `data` TEXT NOT NULL
  );

CREATE TABLE
  IF NOT EXISTS `comment` (
    `commentId` INTEGER NOT NULL PRIMARY KEY,
    `message` TEXT NOT NULL,
    `created` datetime NOT NULL,
    `userId` TEXT NOT NULL REFERENCES `user` (`userId`) ON DELETE NO ACTION ON UPDATE CASCADE,
    `ticketId` INTEGER NOT NULL REFERENCES `ticket` (`ticketId`) ON DELETE CASCADE ON UPDATE CASCADE
  );

CREATE TABLE
  IF NOT EXISTS `file` (
    `fileId` INTEGER NOT NULL PRIMARY KEY,
    `commentId` INTEGER DEFAULT NULL REFERENCES `comment` (`commentId`) ON DELETE SET NULL ON UPDATE CASCADE,
    `mime` TEXT DEFAULT NULL,
    `name` TEXT DEFAULT NULL,
    `filename` TEXT DEFAULT NULL,
    `thumb` TEXT DEFAULT NULL
  );

CREATE TABLE
  IF NOT EXISTS `team` (
    `teamId` INTEGER NOT NULL PRIMARY KEY,
    `name` TEXT NOT NULL DEFAULT ''
  );

CREATE TABLE
  IF NOT EXISTS `ticket` (
    `ticketId` INTEGER NOT NULL PRIMARY KEY,
    `subject` TEXT NOT NULL DEFAULT '',
    `message` TEXT NOT NULL DEFAULT '',
    `priority` INTEGER NOT NULL DEFAULT 1,
    `risk` INTEGER NOT NULL DEFAULT 1,
    `created` datetime NOT NULL,
    `typeId` INTEGER NOT NULL DEFAULT 0 REFERENCES `ticket_type` (`ticketTypeId`) ON DELETE CASCADE ON UPDATE CASCADE,
    `statusId` INTEGER NOT NULL REFERENCES `ticket_status` (`ticketStatusId`) ON DELETE CASCADE ON UPDATE CASCADE,
    `teamId` INTEGER NOT NULL REFERENCES `team` (`teamId`) ON DELETE CASCADE ON UPDATE CASCADE,
    `owner` TEXT NOT NULL REFERENCES `user` (`userId`) ON DELETE CASCADE ON UPDATE CASCADE
  );

CREATE TABLE
  IF NOT EXISTS `ticket_status` (
    `ticketStatusId` INTEGER NOT NULL PRIMARY KEY,
    `name` TEXT NOT NULL DEFAULT ''
  );

CREATE TABLE
  IF NOT EXISTS `ticket_type` (
    `ticketTypeId` INTEGER NOT NULL PRIMARY KEY,
    `name` TEXT NOT NULL DEFAULT '',
    `teamId` INTEGER NOT NULL DEFAULT '' REFERENCES `team` (`teamId`) ON DELETE CASCADE ON UPDATE CASCADE
  );

CREATE TABLE
  IF NOT EXISTS `user` (
    `userId` TEXT NOT NULL PRIMARY KEY,
    `passhash` TEXT DEFAULT NULL,
    `fn` TEXT NOT NULL,
    `ln` TEXT NOT NULL,
    `email` TEXT NOT NULL,
    `permissions` INTEGER NOT NULL DEFAULT 0,
    `src` TEXT NOT NULL
  );

CREATE TABLE
  IF NOT EXISTS `user_team` (
    `userId` TEXT NOT NULL REFERENCES `user` (`userId`) ON DELETE CASCADE ON UPDATE CASCADE,
    `teamId` INTEGER NOT NULL REFERENCES `team` (`teamId`) ON DELETE CASCADE ON UPDATE CASCADE,
    `notifyOnNew` INTEGER NOT NULL DEFAULT 1,
    `notifyOnUpdate` INTEGER NOT NULL DEFAULT 1,
    `notifyOnAssignment` INTEGER NOT NULL DEFAULT 1
  );

CREATE TABLE
  IF NOT EXISTS `user_assigned` (
    `userId` TEXT NOT NULL REFERENCES `user` (`userId`) ON DELETE CASCADE ON UPDATE CASCADE,
    `ticketId` INTEGER NOT NULL REFERENCES `ticket` (`ticketId`) ON DELETE CASCADE ON UPDATE CASCADE
  );

