/*
* This file was generated by a tool.
* Rerun sql-ts to regenerate this file.
*/
export interface DbComment {
  'commentId': number;
  'created': Date;
  'message': string;
  'ticketId': number;
  'userId': string;
}
export interface DbFile {
  'commentId': number | null;
  'fileId': number;
  'filename': string | null;
  'mime': string | null;
  'name': string | null;
  'thumb': string | null;
}
export interface DbSession {
  'data': string;
  'id': string;
}
export interface DbTeam {
  'name': string;
  'teamId': number;
}
export interface DbTicket {
  'created': Date;
  'message': string;
  'owner': string;
  'priority': number;
  'risk': number;
  'statusId': number | null;
  'subject': string;
  'teamId': number;
  'ticketId': number;
  'typeId': number;
}
export interface DbTicketStatus {
  'name': string;
  'ticketStatusId': number;
}
export interface DbTicketType {
  'name': string;
  'teamId': number;
  'ticketTypeId': number;
}
export interface DbUser {
  'email': string;
  'fn': string;
  'ln': string;
  'passhash': string | null;
  'permissions': number;
  'src': string;
  'userId': string;
}
export interface DbUserTeam {
  'teamId': number;
  'userId': string;
}
